import type { Metadata } from "next";
import { Montserrat, Geist_Mono, Anton, Bebas_Neue } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: ["400"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: ["400"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Barques font - Usando archivos locales
const barques = localFont({
  src: [
    {
      path: "../public/fonts/Barques-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Barques-Regular.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-barques",
  fallback: ["serif"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${geistMono.variable} ${barques.variable} ${anton.variable} ${bebasNeue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
